POST http://localhost:7070/accountapi/signup
Content-Type: application/json

{
    "userId": "id",
    "userPassword": "ps",
    "userNickname": "nic",
    "userEmail": "email"
}
###

GET http://localhost:7070/accountapi/userInfo/389117a5-25d9-4a9f-b1fc-c1134a60c585
content-type: application/json

###

POST http://localhost:7070/accountapi/login
Content-Type: application/json

{
    "userId": "id",
    "userPassword": "ps"
}

###

DELETE http://localhost:7070/accountapi/user/389117a5-25d9-4a9f-b1fc-c1134a60c585
content-type: application/json

###




